language: elixir

elixir:
  - 1.5
  - 1.6
  - 1.7

otp_release:
  - 19.3
  - 20.3

env:
  - GLOBAL_MOCK=true
  - GLOBAL_MOCK=false

script:
  - "MIX_ENV=test mix do deps.get, compile, coveralls.travis"
